version: "3.8"

# https://github.com/google/cadvisor/issues/2838#issuecomment-2966600885
# for setting up cAdvisor in MacOS with Apple M Chip
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    platform: linux/aarch64 # Nếu bạn dùng Apple M Chip thì bỏ comment dòng này
    ports:
      - 8080:8080
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro